### ISSUE TITLE
Python 3.12 build error

### ISSUE THREAD

**Issue by willemw12** [andreikop/qutepart#99]
Fails to build with Python 3.12 on Arch Linux: https://aur.archlinux.org/packages/qutepart-git.

After ignoring build warnings "-Wdeprecated-declarations",  "-Wnt-conversion" and "-Wimplicit-function-declaration" (warnings cause build errors), there are still build errors left:

    qutepart/syntax/cParser.c: In function ‘AbstractRuleParams_init’:
    qutepart/syntax/cParser.c:492:55: error: subscripted value is neither array nor pointer nor vector
      492 |         self->textType = PyUnicode_AsUnicode(textType)[0];
          |                                                       ^

When removing all the "[0]" mentioned in the compile error messages, it builds successfully.
